### ISSUE TITLE
Opencar version 3.0.3.6 & php 7.3+

### ISSUE THREAD

**Issue by wewetech** [Knawat/knawat-dropshipping-opencart#75]
We have faced issues using Knawat module in Opencart version 3.0.3.6 with strange functions & actions by the module as listed below:

1- Resetter the Product Options & Attributes to number 1 
2- removes the SEO keywords from the whole
3- Disturbed the function of SEO in the store (sometimes SEO link works & mostly no)

once you remove the module everything works normally on the site and you have to reupdate things manually.

seeking you helo to resolve the issues

**Comment by HeshamIsmail** [comment]
Hello @wewetech ,

Thank you for contacting Knawat support.
Can you please provide further details about the behavior? For example, are you applying changes to Knawat products attributes that get reset after a while due to our extension? Is the SEO added to Knawat products?

It would be really helpful if you provided a few screenshots or a screen recorder for the behavior so we can get the full picture.

For meanwhile, we'll perform a local test in an attempt to replicate the behavior.

Thank you, 
Hesham Ismail

**Comment by HeshamIsmail** [comment]
1-We imported a few products locally.
2-Added new attribute.
3-Activated Crone Job manually.

Result: The new attribute still saved

**Comment by HeshamIsmail** [comment]
This issue will be closed as we didn't hear from customer for more than 2 months.
